/*
 * Generated by JasperReports
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class diagnosis_report_9316a1c43f6101f3d76701c5a495bb9dc93611549fdf8760c272fde0c9fb3954 extends JREvaluator
{


    /**
     *
     */
    private JRFillField field_diagnosis_id = null;
    private JRFillField field_appointment_id = null;
    private JRFillField field_patient_id = null;
    private JRFillField field_patient_name = null;
    private JRFillField field_sex = null;
    private JRFillField field_age = null;
    private JRFillField field_doctor_name = null;
    private JRFillField field_diagnosis = null;
    private JRFillField field_notes = null;
    private JRFillVariable variable_currentDate = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_diagnosis_id = (JRFillField)fm.get("diagnosis_id");
        field_appointment_id = (JRFillField)fm.get("appointment_id");
        field_patient_id = (JRFillField)fm.get("patient_id");
        field_patient_name = (JRFillField)fm.get("patient_name");
        field_sex = (JRFillField)fm.get("sex");
        field_age = (JRFillField)fm.get("age");
        field_doctor_name = (JRFillField)fm.get("doctor_name");
        field_diagnosis = (JRFillField)fm.get("diagnosis");
        field_notes = (JRFillField)fm.get("notes");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_currentDate = (JRFillVariable)vm.get("currentDate");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 8 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "Diagnosis ID: " + ((java.lang.Integer)field_diagnosis_id.getValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = "Appointment ID: " + ((java.lang.Integer)field_appointment_id.getValue()); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = "Date: " + new java.text.SimpleDateFormat("MMMM dd, yyyy").format(((java.util.Date)variable_currentDate.getValue())); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = "Patient ID: " + ((java.lang.Integer)field_patient_id.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "Patient Name: " + (((java.lang.String)field_patient_name.getValue()) != null ? ((java.lang.String)field_patient_name.getValue()) : "N/A"); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "Age: " + (((java.lang.String)field_age.getValue()) != null ? ((java.lang.String)field_age.getValue()) : "N/A"); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Sex: " + (((java.lang.String)field_sex.getValue()) != null ? ((java.lang.String)field_sex.getValue()) : "N/A"); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_diagnosis.getValue()) != null ? ((java.lang.String)field_diagnosis.getValue()) : "No diagnosis available"; //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "Doctor Name: Dr. " + (((java.lang.String)field_doctor_name.getValue()) != null ? ((java.lang.String)field_doctor_name.getValue()) : "N/A"); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_notes.getValue()) != null ? ((java.lang.String)field_notes.getValue()) : "No additional notes"; //$JR_EXPR_ID=18$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 8 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "Diagnosis ID: " + ((java.lang.Integer)field_diagnosis_id.getOldValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = "Appointment ID: " + ((java.lang.Integer)field_appointment_id.getOldValue()); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = "Date: " + new java.text.SimpleDateFormat("MMMM dd, yyyy").format(((java.util.Date)variable_currentDate.getOldValue())); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = "Patient ID: " + ((java.lang.Integer)field_patient_id.getOldValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "Patient Name: " + (((java.lang.String)field_patient_name.getOldValue()) != null ? ((java.lang.String)field_patient_name.getOldValue()) : "N/A"); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "Age: " + (((java.lang.String)field_age.getOldValue()) != null ? ((java.lang.String)field_age.getOldValue()) : "N/A"); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Sex: " + (((java.lang.String)field_sex.getOldValue()) != null ? ((java.lang.String)field_sex.getOldValue()) : "N/A"); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_diagnosis.getOldValue()) != null ? ((java.lang.String)field_diagnosis.getOldValue()) : "No diagnosis available"; //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "Doctor Name: Dr. " + (((java.lang.String)field_doctor_name.getOldValue()) != null ? ((java.lang.String)field_doctor_name.getOldValue()) : "N/A"); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_notes.getOldValue()) != null ? ((java.lang.String)field_notes.getOldValue()) : "No additional notes"; //$JR_EXPR_ID=18$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 8 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "Diagnosis ID: " + ((java.lang.Integer)field_diagnosis_id.getValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = "Appointment ID: " + ((java.lang.Integer)field_appointment_id.getValue()); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = "Date: " + new java.text.SimpleDateFormat("MMMM dd, yyyy").format(((java.util.Date)variable_currentDate.getEstimatedValue())); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = "Patient ID: " + ((java.lang.Integer)field_patient_id.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "Patient Name: " + (((java.lang.String)field_patient_name.getValue()) != null ? ((java.lang.String)field_patient_name.getValue()) : "N/A"); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "Age: " + (((java.lang.String)field_age.getValue()) != null ? ((java.lang.String)field_age.getValue()) : "N/A"); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Sex: " + (((java.lang.String)field_sex.getValue()) != null ? ((java.lang.String)field_sex.getValue()) : "N/A"); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_diagnosis.getValue()) != null ? ((java.lang.String)field_diagnosis.getValue()) : "No diagnosis available"; //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "Doctor Name: Dr. " + (((java.lang.String)field_doctor_name.getValue()) != null ? ((java.lang.String)field_doctor_name.getValue()) : "N/A"); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_notes.getValue()) != null ? ((java.lang.String)field_notes.getValue()) : "No additional notes"; //$JR_EXPR_ID=18$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
